# Generated by Django 4.2.11 on 2024-04-30 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0003_alter_answertag_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnswer",
            fields=[
                (
                    "answer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.answer",
                    ),
                ),
                ("citation", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.answer",),
        ),
    ]
