# Generated by Django 4.2.11 on 2024-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aianswer",
            options={"verbose_name": "AI-answer", "verbose_name_plural": "AI-answer"},
        ),
    ]
