# Generated by Django 4.2.11 on 2024-05-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="grade",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="(0 = not clear, 5 = very clear)",
                verbose_name="Do you find this article clearly explained and easy to follow?",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="reliability_grade",
            field=models.PositiveSmallIntegerField(
                help_text="(0 = not reliable, 5 = very reliable)",
                verbose_name="Do you find this AIHelpdesk article reliable?",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_age",
            field=models.PositiveSmallIntegerField(
                blank=True, verbose_name="What is your age?"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_email",
            field=models.EmailField(
                blank=True,
                help_text="We will forward the expert's response when we receive it.",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_name",
            field=models.TextField(blank=True, verbose_name="What is your name?"),
        ),
    ]
