# Generated by Django 4.2.11 on 2024-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_grade_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="user_age",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="What is your age?"
            ),
        ),
    ]
